version: '1.0'
include:
  - test/descriptions/*.md
  - descriptions/*.md
  - README.md
  - CLAUDE.md
  - test/descriptions/overview.md
  - test/descriptions/architecture.md
  - test/descriptions/api-reference.md
  - test/descriptions/getting-started.md
  - test/descriptions/troubleshooting.md
  - test/descriptions/deployment.md
exclude:
  - descriptions/actionable/NEXT_STEPS.md
  - node_modules/
  - '*.log'
  - .git/
  - temp-*
  - scripts/
  - package.json
  - package-lock.json
  - .mcp-visibility.json
settings:
  priority_files:
    - llms.txt
    - README.md
    - CLAUDE.md
  max_file_size: 1048576
  include_metadata: true
