name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create site structure
        run: |
          # Create a simple directory structure for the site
          mkdir -p _site
          
          # Copy all visible files to _site directory
          if [ -f "README.md" ]; then
            cp README.md _site/index.md
          fi
          
          # Copy all other files that exist in main branch
          find . -name "*.md" -not -path "./_site/*" -not -path "./.git/*" -exec cp {} _site/ \;
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4